name: flash_card
description: "A flash card app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.8.1
  flutter_flip_card: ^0.0.6
  package_rename: ^1.10.0
  cupertino_icons: ^1.0.8

  font_awesome_flutter: ^10.12.0
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.4.0
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  http: ^1.2.2
  uuid: ^4.4.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "images/logo.png"
  adaptive_icon_foreground: "images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - images/avatar.jpg
    - images/logo.png
    - images/google_logo.png
    - images/welcome.png

flutter_native_splash:
  color: "#FFFFFF"
  image: images/logo.png
  android: true
  ios: false

